default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: urlshortner_development
  # url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: urlshortner_test

production:
  # <<: *default
  url: <%= ENV['DATABASE_URL'] %>
